Debugging

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -332,7 +332,7 @@ jobs:
     steps:
       # - attach_workspace:
       #     at: /tmp/saveme
-      - checkout
+      # - checkout
       # - run:
       #     name: Install system dependencies
       #     command: |
@@ -348,31 +348,28 @@ jobs:
             URL="http://udapeople-frontend-deployment-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/#/employees"
             if curl -s ${URL} | grep "Welcome"
             then
-              return 0
+              exit 0
             else
-              return 1
+              exit 1
             fi
       - run:
           name: Smoke test on backend
           command: |
-            file=/tmp/saveme/backend_url.txt
-            echo $file
-            echo "http://$(cat $file):3030/api/status"
-
-            aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query "Reservations[*].Instances[*].[PublicDnsName]" \
-              --output text
-
-            BACKEND_URL=$(aws ec2 describe-instances \
+            export BACKEND_URL=$(aws ec2 describe-instances \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query "Reservations[*].Instances[*].[PublicDnsName]" \
               --output text)
 
+            if curl http://${BACKEND_URL}:3030/api/status | grep '"status": "ok"'
+            then
+             exit 0
+            else
+              echo 'Backend smoke test failed due to an invalid check'
+              exit 1
+            fi 
+
             echo $BACKEND_URL
             echo "http://${BACKEND_URL}:3030/api/status"
-
-            curl "http://${BACKEND_URL}:3030/api/status"
 
       - destroy-environment
       - revert-migrations
